# Generated by Django 5.2.7 on 2025-10-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=64)),
                ('ext_id', models.CharField(blank=True, max_length=128)),
                ('period_days', models.FloatField(blank=True, null=True)),
                ('duration_hours', models.FloatField(blank=True, null=True)),
                ('depth_ppm', models.FloatField(blank=True, null=True)),
                ('teff_K', models.FloatField(blank=True, null=True)),
                ('mag', models.FloatField(blank=True, null=True)),
                ('label_predicho', models.CharField(blank=True, max_length=32, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
