# Generated by Django 5.2.7 on 2025-10-05 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('RESEARCHER', 'Investigador'), ('NOVICE', 'Novato')], default='NOVICE', max_length=20, verbose_name='Tipo de Usuario')),
                ('institution', models.CharField(blank=True, max_length=200, null=True, verbose_name='Institución')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biografía')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
